server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://139.198.181.54:3306/hmdp?useSSL=false
    username: root
    password: Dcp#7ujm
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 139.198.181.54
    port: 5672
    username: github
    password: 123456
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo