server:
  port: 8080
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://139.198.181.54:3306/leetcode?useSSL=false
    username: root
    password: Dcp#7ujm
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 139.198.181.54:8848
      discovery:
        cluster-name: HZ #配置集群名称，也就是机房位置，例如：HZ 杭州
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url: # eureka地址信息
#      defaultZone: http://localhost:10000/eureka