server:
  port: 8080

spring:
  application:
    name: reggie-take-out
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://139.198.181.54:3306/hmdp?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai #&zeroDateTimeBehavior=convertToNull
      username: root
      password: Dcp#7ujm
  redis:
    host: 139.198.181.54
    port: 6379
    password: Dcp#7ujm
  cache:
    redis:
      time-to-live: 1800000 # 设置缓存有效期

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
