server:
  port: 10012

spring:
  rabbitmq:
    host: 139.198.181.54 #IP
    port: 5672 #端口
    username: guest #用户名
    password: guest #密码
    virtual-host: /
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    template:
      mandatory: true

logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    com.xiaomi: debug