server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://139.198.181.54:3306/leetcode?useSSL=false
    username: root
    password: Dcp#7ujm
    driver-class-name: com.mysql.jdbc.Driver
  boot:
    admin:
      client:
        url: localhost:10000
        instance:
          prefer-ip: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url: # eureka地址信息
#      defaultZone: http://localhost:10000/eureka