server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 139.198.181.54:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**