server:
  port: 9002

spring:
  application:
    name: tool-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  thymeleaf:
    servlet:
      content-type: text/html;
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /**
  redis:
    host: 139.198.181.54
    port: 6379
    password: null
    lettuce:
      pool:
        max-active: 8 #最大连接
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 1000ms #等待时间
