server:
  port: 8081
spring:
  application:
    name: redis-dianping
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.198.181.54:3306/leetcode?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 139.198.181.54
    port: 6379
    password: 123321
    lettuce: # redis连接池
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.github.pojo # 别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.github: debug